### ISSUE TITLE
MainActivity 的ButterKnife初始化是不是可以注释了，基类已经有了bind

### ISSUE THREAD

**Issue by github0911** [WuXiaolong/AndroidMVPSample#11]
/**
 * 由Activity/Fragment实现View里方法，包含一个Presenter的引用
 * Created by WuXiaolong
 * on 2015/9/23.
 * github:https://github.com/WuXiaolong/
 * weibo:http://weibo.com/u/2175011601
 * 微信公众号：吴小龙同学
 * 个人博客：http://wuxiaolong.me/
 */
public class MainActivity extends MvpActivity<MainPresenter> implements MainView {

    @Bind(R.id.text)
    TextView text;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
        initToolBarAsHome("MVP+Retrofit+Rxjava");

    }

**Comment by WuXiaolong** [comment]
可以的，因为我用了ButterKnife插件，默认都生成ButterKnife.bind(this);因此基类我也没有删除
